### ISSUE TITLE
不知道有没有时间将这个字体的中文字符使用华文楷体来做？成一个新字体

### ISSUE THREAD

**Issue by WingDust** [laishulu/Sarasa-Term-SC-Nerd#10]

**Comment by laishulu** [comment]
https://github.com/laishulu/Sarasa-Term-SC-Nerd#%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90%E5%AD%97%E4%BD%93

自己照这个跑一下，当然，相关的文件名，字体名，需要自己改。
