### ISSUE TITLE
使用这字体导致 txt 文档打开十分缓慢

### ISSUE THREAD

**Issue by xjArea** [laishulu/Sarasa-Term-SC-Nerd#14]
字体是很好的, 但 Windows10 的 txt 文档使用这个字体后, 文件打开速度就变得十分缓慢, 一个几 KB 的文件, 都经常要转个几秒甚至是十几秒才能打开, 是什么因素导致了这种情况哇 ?

**Comment by lindexi** [comment]
预计渲染的路径复杂了，我刚刚下载这个字体准备用，也感觉卡但没你这么卡

**Comment by xjArea** [comment]
机器的性能不同, 性能好的可能就影响小一点, 不过这个迟缓还挺烦人的, 不知道有没有改进的余地…

**Comment by lindexi** [comment]
坐等哪位大佬咯

**Comment by laishulu** [comment]
已更新sarasa和nerd到最新的上游版本。

**Comment by laishulu** [comment]
你可能需要unhint版本的sarasa。不过我这里没有提供。
你可以按照readme用unhint版本自己去打包。

**Comment by laishulu** [comment]
提供了unhinted版本，
可去 https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases 下载安装试用。

**Comment by lindexi** [comment]
多谢大佬 @laishulu

**Comment by laishulu** [comment]
> 多谢大佬 @laishulu

测试了没，正常了or还是慢？反馈一下？

**Comment by xjArea** [comment]
在 Windows10 系统中安装 Unhinted 版本的 SarasaTermSCNerd-Regular.ttf, 发现中文的字间距变得很大, 两个中文之间的水平间隙甚至能多容纳一个半角英文, 是哪里的设置出问题了吗? 但是半角的英文就很正常呢, 下面是 txt 实测截图: 

![image](https://github.com/user-attachments/assets/fd66bad8-7a69-44d8-ac0c-84712640f4ee)

**Comment by laishulu** [comment]
这个问题，
只在unhinted版本中，
普通版本没有，
是吧？

unhinted版本我没有测过，
我以为其他方面都和普通版本一样，
就直接打补丁了。
我抽空研究一下~~~

**Comment by xjArea** [comment]
普通版本我没有测试, 只是单独装了 unhinted 版本的 Regular.ttf, 因为旧版本除了加载缓慢之外也没有其他问题了… 😅

**Comment by lindexi** [comment]
@laishulu 似乎前后没有多少变化，还是有些卡，且出现了中文字符的字后间距过大问题

**Comment by laishulu** [comment]
那也可是别的问题。

本项目以前的一个补丁，
（修正windows下不正常的问题）
我上次升级的时候，
在新版的官方nerd font patcher里看到了相关代码(但不完全一致)，
我就从本项目里面给删掉了。

我觉得也可能是因为，
官方的那部分还是有问题。

麻烦你测一下普通版的字体有没有间距过大的问题，
不行的话，我再把本项目以前的补丁打回来。

**Comment by laishulu** [comment]
> @laishulu 似乎前后没有多少变化，还是有些卡，且出现了中文字符的字后间距过大问题

卡顿没有提升啊，那我就不知道了。

如果你屏幕的dpi不高，
会调用hint进行字形微调以改善显示效果，
如果这个额外的步骤造成你电脑卡顿，
改用unhint字体就可以避免。

如果卡顿不是这个原因造成的，
那unhint字体就没有帮助。

**Comment by lindexi** [comment]
@laishulu 这个版本也有字间距问题： https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.1.0/SarasaTermSCNerd.ttf.7z

使用 NotePad 的显示效果如下图所示

![](https://github.com/user-attachments/assets/ed8b7863-9d7f-40c0-aca2-b696694f3d17)

**Comment by lindexi** [comment]
> > @laishulu 似乎前后没有多少变化，还是有些卡，且出现了中文字符的字后间距过大问题
> 
> 卡顿没有提升啊，那我就不知道了。
> 
> 如果你屏幕的dpi不高， 会调用hint进行字形微调以改善显示效果， 如果这个额外的步骤造成你电脑卡顿， 改用unhint字体就可以避免。
> 
> 如果卡顿不是这个原因造成的， 那unhint字体就没有帮助。

原来如此，多谢大佬科普

**Comment by laishulu** [comment]
> @laishulu 这个版本也有字间距问题： https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.1.0/SarasaTermSCNerd.ttf.7z
> 
> 使用 NotePad 的显示效果如下图所示
> 
> ![](https://private-user-images.githubusercontent.com/16054566/385168969-ed8b7863-9d7f-40c0-aca2-b696694f3d17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTQwNDUsIm5iZiI6MTczMTM5Mzc0NSwicGF0aCI6Ii8xNjA1NDU2Ni8zODUxNjg5NjktZWQ4Yjc4NjMtOWQ3Zi00MGMwLWFjYTItYjY5NjY5NGYzZDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA2NDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhY2UzNTU5ZTYyNmQyMDdiOTJiNmIwMzJmZmQ3ZjhiYzA3MWNiMTRlMmQyNTgyMWFmYTA0ZjkxZTFmM2E4YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9kVFGCZy2sJlVPPDZKFw82n-BNB-Xqyyggino1lDhPA)



> @laishulu 这个版本也有字间距问题： https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.1.0/SarasaTermSCNerd.ttf.7z
> 
> 使用 NotePad 的显示效果如下图所示
> 
> ![](https://private-user-images.githubusercontent.com/16054566/385168969-ed8b7863-9d7f-40c0-aca2-b696694f3d17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTQxNzcsIm5iZiI6MTczMTM5Mzg3NywicGF0aCI6Ii8xNjA1NDU2Ni8zODUxNjg5NjktZWQ4Yjc4NjMtOWQ3Zi00MGMwLWFjYTItYjY5NjY5NGYzZDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA2NDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NDEwYjlhMTA4Y2RkNGI2N2RjYzBiOWEyZTIxNTExM2M4NjAzZTMyOGVkNDhmMTVkZjRlMWExMTA0NDhhZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.guOQuZMCDiJYrvMjfbtZZFpzEJ-BaBCRNNv_FEfXgsY)



哦。
那就是官方加进去的补丁代码不行，
我重新把补丁加回来。

**Comment by xjArea** [comment]
> @laishulu 这个版本也有字间距问题： https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.1.0/SarasaTermSCNerd.ttf.7z
> 
> 使用 NotePad 的显示效果如下图所示
> 
> ![](https://private-user-images.githubusercontent.com/16054566/385168969-ed8b7863-9d7f-40c0-aca2-b696694f3d17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTQwNDUsIm5iZiI6MTczMTM5Mzc0NSwicGF0aCI6Ii8xNjA1NDU2Ni8zODUxNjg5NjktZWQ4Yjc4NjMtOWQ3Zi00MGMwLWFjYTItYjY5NjY5NGYzZDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA2NDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhY2UzNTU5ZTYyNmQyMDdiOTJiNmIwMzJmZmQ3ZjhiYzA3MWNiMTRlMmQyNTgyMWFmYTA0ZjkxZTFmM2E4YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9kVFGCZy2sJlVPPDZKFw82n-BNB-Xqyyggino1lDhPA)

你这是把字体设置为系统默认字体了? 这样会影响到系统的整体速度吗? 真是个大胆的玩法啊. 😮

**Comment by lindexi** [comment]
@xjArea 没有吧，这里应该只影响 NotePad 吧，我也不太确定哈。但是即使是整个系统，问题也不大，我截图之后又设置回微软雅黑了

**Comment by laishulu** [comment]
>https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.1.0/SarasaTermSCNerd.ttf.7z

这个就是普通版本，带hint的。

**Comment by laishulu** [comment]
我下次用windows虚拟机自己测测，就是在notepad里，就可以复现问题，是吧？

**Comment by lindexi** [comment]
@laishulu 是的，直接打开 NotePad 设置字体即可复现（我不知道这里设置的字体是否会影响系统其他的功能，不过虚拟机的话就随意了）

**Comment by laishulu** [comment]
我测试了win 10和win 11，都是正常的。
渲染速度和间距都没有问题，
不知道是不是因为我是苹果的视网膜屏幕，
DPI高？
这就不好定位问题了。

**Comment by lindexi** [comment]
@laishulu 我的 DPI 是百分百的，我的是戴尔的小屏幕

**Comment by xjArea** [comment]
> 我测试了win 10和win 11，都是正常的。 渲染速度和间距都没有问题， 不知道是不是因为我是苹果的视网膜屏幕， DPI高？ 这就不好定位问题了。

在 txt 中使用这个字体也是正常的吗? 我上面那个截图就是在 txt 文档的环境中出现的…

**Comment by laishulu** [comment]
> > 我测试了win 10和win 11，都是正常的。 渲染速度和间距都没有问题， 不知道是不是因为我是苹果的视网膜屏幕， DPI高？ 这就不好定位问题了。
> 
> 在 txt 中使用这个字体也是正常的吗? 我上面那个截图就是在 txt 文档的环境中出现的…

我打开系统自带的notepad测试的。
纯txt

**Comment by laishulu** [comment]
![CleanShot 2024-11-12 at 23 41 24@2x](https://github.com/user-attachments/assets/6d64ef20-a884-4533-9fb1-e612d5958d30)

**Comment by xjArea** [comment]
Emmm, 真是个奇怪的问题… 🤔

**Comment by laishulu** [comment]
我又检查了代码，宽度这块，官方的patch还是不行，还是要自己的打补丁。
我现在把这块加回来，重新生成字体。
完成之后，我来这里回复一下。

**Comment by laishulu** [comment]
v2.1.1修正了宽度问题。
但是，
渲染慢的问题，如果unhinted都不能解决的话，
那我就没有头绪了。

**Comment by lindexi** [comment]
![](https://github.com/user-attachments/assets/d5a5e9bd-b515-47a0-9881-2e3c07922809)

下载安装 2.1.1 版本，宽度解决

**Comment by xjArea** [comment]
![image](https://github.com/user-attachments/assets/c5691143-09b9-40d7-b9ec-241d9e12973a)

使用 V2.1.1, 宽度没问题了, 
单装 Regular.ttf 版本, txt 文档启动速度似乎也有所提升. ( •̀ ω •́ )✧

**Comment by xjArea** [comment]
实测发现文档启动速度确实有所提升, 但新版本有些中文糊掉了, 笔画没有旧版那么清晰, 这个还有改进的余地吗? 下面是新旧版本的 Gif 截图, 可以比对两个版本之间的字体细节, 例如第一行的"朱"字和第二行的"思"字, 都有笔划模糊的情况: 

![Sarasa](https://github.com/user-attachments/assets/a0f1e858-375c-4224-b641-dc9f895d6a4b)

**Comment by laishulu** [comment]
一个是普通版本，一个是unhint版本吧？
这个就是没有办法了。

在低dpi屏幕上，
普通版本通过微调字形，可以更清晰，
但是这个过程要耗费计算资源。

如果在你机子卡，那就只能上unhint版本，
代价就是影响清晰度。

高dpi的屏幕不需要微调字形。

**Comment by xjArea** [comment]
原来如此, 也能凑活用啦…
不过屏幕的 DPI, 多少才算高啊, 非得到视网膜屏的程度? 😅
