### ISSUE TITLE
Font size为奇数时TAB的宽度似乎有问题

### ISSUE THREAD

**Issue by 25minutes** [laishulu/Sarasa-Term-SC-Nerd#15]
首先感谢制作这么好的字体，网上找了许久，这是我找到唯一的一款在各个font size中英文都能很好对齐的字体

目前使用下来只发现Font size为奇数时TAB的宽度似乎有问题，出现了对齐的问题

我在text editor设置一个tab对应两个空格
![scr-1](https://github.com/laishulu/Sarasa-Term-SC-Nerd/assets/26299733/d345af0e-09a3-4c2f-9400-ee070b954abb)

Font size为偶数时对齐完全正常
![scr-2](https://github.com/laishulu/Sarasa-Term-SC-Nerd/assets/26299733/dda4b880-41e2-416a-bb73-1c343c9db526)

Font size为奇数就对不齐了
![scr-3](https://github.com/laishulu/Sarasa-Term-SC-Nerd/assets/26299733/861a2004-7996-4bc9-b9e8-7ff2bcc8a738)

放在一起对比测试，看上去是TAB导致的问题，空格是正常的
![scr-4](https://github.com/laishulu/Sarasa-Term-SC-Nerd/assets/26299733/c2463410-ac80-441b-a081-9f5daab42c72)

**Comment by laishulu** [comment]
已更新sarasa和nerd到最新的上游版本。
