### ISSUE TITLE
与Mathtype冲突

### ISSUE THREAD

**Issue by EVANGELION-Air** [laishulu/Sarasa-Term-SC-Nerd#16]
在windows下只要安装Sarasa-Term-SC-Nerd，Mathtype就会闪退打不开。

原版更纱黑体的早些版本与Mathtype有冲突，是完全相同的情况：

<https://www.zhihu.com/question/388742752>

但是，目前的更纱黑体0.41.4版本已经没有该问题，推测同步更新上游就会解决问题

**Comment by laishulu** [comment]
已更新sarasa和nerd到最新的上游版本。
