### ISSUE TITLE
seems emoji chars not fixed width?

### ISSUE THREAD

**Issue by yurenchen000** [laishulu/Sarasa-Term-SC-Nerd#17]
## test text
without emoji it's fine:

```
| Month月  | Savings金额 | test |
| -------- |:-----------:| ----:|
| January  |  啊啊$250   |   ok |
| February |    哦$80    |   ok |
| March    |   呃$420    | pass |
|          |      -      |      |
|          |             |      |
```

but with emoji chars, width broken

```
| Month月  | Savings金额 | test |
| -------- |:-----------:| ---- |
| January  |  😱😱$250   | ❌   |
| February |    🙂$80    | ✅   |
| March    |    $420     | ❌   |
|          |      -      |      |
|          |             |      |
```

## preview 
in gnome-editor  VS kitty-terminal
// in terminal is fixed witdh render, display result indicate the test text is aligned

![mono_test-](https://github.com/laishulu/Sarasa-Term-SC-Nerd/assets/8458213/986098b5-46cc-4f2c-aff3-17927946202d)

## Am I missing something?

what should I do?

**Comment by laishulu** [comment]
https://github.com/be5invis/Sarasa-Gothic/issues/44#issuecomment-420530312

Sarasa字体里面是没有emoji的。你的终端里，是fallback到别的字体了。

在emacs里面指定本字体的话，会发现emoji找不到字体。
![Snipaste_2023-08-05_12-35-21](https://github.com/laishulu/Sarasa-Term-SC-Nerd/assets/1224321/3d273ab1-f5b2-4a91-9279-7cde362d8fa9)

但是你看`金`字的话，


![Snipaste_2023-08-05_12-46-29](https://github.com/laishulu/Sarasa-Term-SC-Nerd/assets/1224321/c64df31a-7956-4233-ad09-c45d84da9d7f)

**Comment by yurenchen000** [comment]
@laishulu 

Thanks for reply.

Your point is clarify, 
 The Sarasa font is no responsibility for the width of emoji characters.

----

As a end user I still want to figure out a solution that
 make emoji got same width with CJK chars (in Sarasa).

Any advice would be appreciated.

----

For now, all I know is
 Patch my text editor or web application,
 Renders each emoji chars one by one in their own cells (to limit char width).
 like the common practice in terminal programs.
