### ISSUE TITLE
更新上游依赖版本

### ISSUE THREAD

**Issue by oshenyang** [laishulu/Sarasa-Term-SC-Nerd#19]
能适配下最新的上游字体和NerdFont吗？
我用最新上游版本打包有错误。

**Comment by taynpg** [comment]
顶一个，好像是目前能找到的唯一能在windows的cmd GBK环境下使用支持Nerd的字体，但是有少数的图标不支持，要是能适配一下最新上游字体和NerdFont就完美了。
![image](https://github.com/laishulu/Sarasa-Term-SC-Nerd/assets/59216127/3a684ce9-a415-453b-9376-3dc086b211b8)

**Comment by mzr1996** [comment]
> 顶一个，好像是目前能找到的唯一能在windows的cmd GBK环境下使用支持Nerd的字体，但是有少数的图标不支持，要是能适配一下最新上游字体和NerdFont就完美了。 ![image](https://private-user-images.githubusercontent.com/59216127/315943681-3a684ce9-a415-453b-9376-3dc086b211b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTA5NjgsIm5iZiI6MTcyMjI1MDY2OCwicGF0aCI6Ii81OTIxNjEyNy8zMTU5NDM2ODEtM2E2ODRjZTktYTQxNS00NTNiLTkzNzYtM2RjMDg2YjIxMWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwNTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZmVjMWI0YzllNmU1N2JlNTZlYzIzZGRhZDg4MTU4MTE1ODQyNTI2NDY0MTc5NTNmNmM3MmE5Mjg1Yzg2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.47wSgkRifoipxiQxztUWblae74dyQLTSXAElf2smsxE)

我 fork 了一版，更新了上游，但是没有在 windows 和 mac 上测试
https://github.com/mzr1996/Sarasa-Term-SC-Nerd

**Comment by taynpg** [comment]
> > 顶一个，好像是目前能找到的唯一能在windows的cmd GBK环境下使用支持Nerd的字体，但是有少数的图标不支持，要是能适配一下最新上游字体和NerdFont就完美了。 ![image](https://private-user-images.githubusercontent.com/59216127/315943681-3a684ce9-a415-453b-9376-3dc086b211b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTA5NjgsIm5iZiI6MTcyMjI1MDY2OCwicGF0aCI6Ii81OTIxNjEyNy8zMTU5NDM2ODEtM2E2ODRjZTktYTQxNS00NTNiLTkzNzYtM2RjMDg2YjIxMWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwNTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZmVjMWI0YzllNmU1N2JlNTZlYzIzZGRhZDg4MTU4MTE1ODQyNTI2NDY0MTc5NTNmNmM3MmE5Mjg1Yzg2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.47wSgkRifoipxiQxztUWblae74dyQLTSXAElf2smsxE)
> 
> 我 fork 了一版，更新了上游，但是没有在 windows 和 mac 上测试 https://github.com/mzr1996/Sarasa-Term-SC-Nerd

试了一下，非常棒（windows环境），兄弟666。
![1722255875626](https://github.com/user-attachments/assets/56ab545c-3348-4d4c-9878-9c9f204651b4)

**Comment by laishulu** [comment]
已更新sarasa和nerd到最新的上游版本。
