### ISSUE TITLE
有图标与文字沾连在一起

### ISSUE THREAD

**Issue by bbenchen** [laishulu/Sarasa-Term-SC-Nerd#21]
![image](https://github.com/user-attachments/assets/4e109f20-d5c6-4b44-993d-9298f3a43f4f)

**Comment by bbenchen** [comment]
使用 JetBrainsMono Nerd Font 则不会出现该问题

**Comment by laishulu** [comment]
你把那个过宽的图标贴到这里来，方便我在本机上调试。
问题可能出现在拉伸上面。

**Comment by laishulu** [comment]
找出原因了。。这个是material design的图标。
因为material desgign的图标数量太多，在中文字体上打补丁，会导致字符数量溢出 65535 。
所以，在英文字体上用这个图标没问题，但是在中文字体上就没有办法完整都打补丁进去。
本字体，在打补丁的时候，将material desgin有意识地跳过了。

有一个办法，就是只选择部分material design的图标打补丁进去，但是怎么选取是个问题。

**Comment by laishulu** [comment]
v2.3.0，在6896个material design的图标中，把前5724个[0xF0001, 0xF165C]打包进去，塞满字体的总字数上限。
像你截图中的：`nf-md-folder_download`(f024d) `nf-md-folder_music`(f1359) 都在里面。
这个问题修复了。

**Comment by laishulu** [comment]
修正版，在material design的图标中跳选，以确保`nf-md-folder_`相关图标[0xf19e8-0xf19fd]都被纳入。

**Comment by bbenchen** [comment]
@laishulu 感谢，感谢
