### ISSUE TITLE
没有monospace字体

### ISSUE THREAD

**Issue by YosakuraTohu** [laishulu/Sarasa-Term-SC-Nerd#4]
如题，更新之后发现所有的Monospace的字体全部都没有了。

**Comment by YosakuraTohu** [comment]
可能解释的不是很清楚，AUR源上的字体安装好后没有等宽字体，设置为终端字体会变得非常奇怪。
![Uploading 8800845C-C772-4527-9055-AD6AD9CA1CE1.jpeg…]()
![Uploading 8E5ECDAA-88E9-42B1-A16B-1829547AAC6A.jpeg…]()

**Comment by YosakuraTohu** [comment]
可能解释的不是很清楚，AUR源上的字体安装好后，没有等宽字体，设置为终端字体会变得非常奇怪。
![9668C595-CD29-45A0-A258-C58DC4709789](https://user-images.githubusercontent.com/96331099/222799157-cdc8a163-c51e-41f5-93cd-008e580072ee.jpeg)
![967723D8-1151-471C-B58B-11A24093485E](https://user-images.githubusercontent.com/96331099/222799195-c0c55b0f-97f4-4a4f-8a5f-3b70914a0b3c.jpeg)

**Comment by laishulu** [comment]
你这个截屏里面不是本项目的字体。

AUR上没有这个字体，
之前基于Sarasa Mono做的字体，社区给放到AUR上。
后来那个字体作废，基于Sarasa Term重新做了。
AUR上的源已失效，
README上已经删掉了AUR安装说明。

手工下载安装吧，
或者社区谁给contribute到AUR上。
我没用过AUR。
