### ISSUE TITLE
中文很舒服但icon好小=。=

### ISSUE THREAD

**Issue by Ronny200** [laishulu/Sarasa-Term-SC-Nerd#5]
中文没得说真的舒服，就是在windows terminal中显示的图标很小，现在用的也是国人改的mono sc nerd,图标少了点。加油

话说有没有办法中文用这个，英文好窄换fira

**Comment by laishulu** [comment]
你不会用的是我之前做的mono sc nerd吧？
之前快1K 个 star了。
那个就是图标少了点。

我后来改成基于Term重新做，
是因为Sarasa的作者这么建议的
https://github.com/be5invis/Sarasa-Gothic/issues/317

**Comment by Ronny200** [comment]
是的。。fira-code的图标大小刚刚好。哈哈
所以这个图标只能这样了？

**Comment by Ronny200** [comment]
好哒，感谢回复，先这么用着，现在两个窗口，一个firacode敲代码舒服点，一个是你这个有中文的地方用

**Comment by laishulu** [comment]
我又研究了一下，还是应当提供一个宽图标的版本。
这两天我会提交一个新版本。

**Comment by transtone** [comment]
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Mononoki 这个字体的icon大小比较合适，本字体的还是太小了。
