### ISSUE TITLE
我在win11 windows terminal下使用好像并没有对齐

### ISSUE THREAD

**Issue by Ronny200** [laishulu/Sarasa-Term-SC-Nerd#9]
我在win11 windows terminal下使用好像并没有对齐，当然比其他字体好很多了
![20230428-225419](https://user-images.githubusercontent.com/23441656/235182466-49975b8b-d042-4f84-b4cc-2f6eb2a1543f.png)

**Comment by laishulu** [comment]
你这截屏，对的挺齐的啊？
你觉得哪里不齐？

**Comment by Ronny200** [comment]
> 你这截屏，对的挺齐的啊？ 你觉得哪里不齐？

是我看错了。。就那个ce6.8那里，是标点造成的，哈哈，其他都很齐

**Comment by laishulu** [comment]
`.`占一个英文字符宽度，😂
